project_id: "261564"
api_token_env: BLOOM_CROWDIN_TOKEN
preserve_hierarchy: true
files: [
        {
            "source": "BloomLibrary.org/*.json",
            "translation": "../%two_letters_code%/BloomLibrary.org/%original_file_name%",
        },


    ]
