name: Build and Deploy

on:
    push:
        branches:
            - master
            - release
            - embed
    workflow_dispatch: # Allows manual triggering of the workflow

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install dependencies
              run: yarn install --frozen-lockfile --network-timeout 1000000000

            # Not yet
            # - name: Upload translations to Crowdin
            #   if: github.ref == 'refs/heads/release'
            #   # Push any new code-based strings to Crowdin
            #   run: crowdin-dangerous-upload
            #   env:
            #     bloomCrowdinApiToken: ${{ secrets.BLOOM_CROWDIN_TOKEN }}

            - name: Download translations from Crowdin
              run: yarn crowdin-download
              env:
                  bloomCrowdinApiToken: ${{ secrets.BLOOM_CROWDIN_TOKEN }}

            - name: Build
              run: |
                  if [ "${{ github.ref }}" == "refs/heads/master" ]; then
                    yarn build:ci:alpha
                  else
                    yarn build:ci
                  fi

            - name: Run tests
              run: yarn test:ci

            # Not yet
            # - name: Deploy to S3
            #   run: |
            #     aws s3 cp path/to/build/artifacts s3://your-bucket-name --recursive
            #   env:
            #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
