name: Lighthouse CI
on:
    push:
        branches:
            - master
jobs:
    lighthouse:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Audit URLs using Lighthouse
              uses: treosh/lighthouse-ci-action@v3
              with:
                  urls: |
                      https://alpha.bloomlibrary.org
                      https://alpha.bloomlibrary.org/covid19
                  runs: 3
                  budgetPath: ./budget.json # test performance budgets
                  uploadArtifacts: true # save results as an action artifacts
                  temporaryPublicStorage: true # upload lighthouse report to the temporary storage
